import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@material-ui/core/Button';
import { useRouter } from "next/router";
export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>The Code Challange</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         The Code Challange
        </h1>

        <p className={styles.description}>
        Do you have what it takes?
        </p>


        <Button variant="contained" color="primary" onClick={()=>router.push("/login")} style={{marginBottom:'15px', background:'black'}}>
       Login
      </Button>
      
      
      <Button variant="contained" color="secondary" color="secondary" onClick={()=>router.push("/signup")} style={{background:'white', color:'black'}}>
        Register 
      </Button>
  
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <strong className={styles.logo}>
            CarlosP
          </strong>
        </a>
      </footer>
    </div>
  )
}
